version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - sockets:/app/tmp/sockets
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /var/tmp
      - sockets:/app/tmp/sockets
    tty: true
    depends_on:
      - db
    extends:
      file: ./docker/rails/password.yml
      service: password

  db:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  sockets:
